### ISSUE TITLE
Multi-wallet support

### ISSUE THREAD

**Issue by RedVelvetZip** [rsksmart/rsk-cli#17]
The CLI only supports one wallet. Adding a new wallet overwrites the rootstock-wallet.json key storage. Testing environments require interaction from multiple wallets, so I propose adding support for multiple keypairs and turning the rootstock-wallet.json into an array of Wallet object types

the /src/commands/wallet.ts file would be adjusted to parse the wallet json array to see if multiple exist, then let users choose which to 'sign in' to

edit property of InquirerAnswers
swap out `useExistingWallet?: boolean;` for `selectedWalletIndex?: number;`

create new type for wallet
```
type Wallet = {
  address: string;
  encryptedPrivateKey: string;
  iv: string;
};
```

load the wallet array
```
let wallets: Wallet[] = [];

    // Check if the wallet file already exists
    if (fs.existsSync(walletFilePath)) {
      const fileContent = fs.readFileSync(walletFilePath, "utf8");

      // Parse the content if not empty and ensure it's a valid array
      if (fileContent.trim().length > 0) {
        wallets = JSON.parse(fileContent);

        if (!Array.isArray(wallets)) {
          throw new Error("Malformed wallet file. Expected an array.");
        }
      }
    }
```

If wallet(s) exist, prompt user to choose one
```
// If wallets are found, prompt the user to select one
if (wallets.length > 0) {
      const walletChoices = wallets.map((wallet, index) => ({
        name: wallet.address,
        value: index,
      }));

      const walletSelectionQuestion: any = [
        {
          type: "list",
          name: "selectedWalletIndex",
          message: "🔍 Multiple wallets found. Please select a wallet:",
          choices: walletChoices,
        },
      ];

      const { selectedWalletIndex } = await inquirer.prompt<InquirerAnswers>(
        walletSelectionQuestion
      );
      const selectedWallet = wallets[selectedWalletIndex];

      console.log(chalk.green("🎉 Using the selected wallet."));
      console.log(
        chalk.white(`📄 Address:`),
        chalk.green(`${chalk.bold(selectedWallet.address)}`)
      );
      return;
    }
```

if the user chooses to 1. create a new wallet or 2. store a private key, adjust logic to account for the wallet array
```
// Add new wallet to the array
      wallets.push(walletData);

      // Write the array to the file
      fs.writeFileSync(
        walletFilePath,
        JSON.stringify(wallets, null, 2),
        "utf8"
      );
      console.log(chalk.green(`💾 Wallet saved securely at ${walletFilePath}`));
      return;
```

**Comment by chrisarevalodev** [comment]
Hey! multi-wallet support was added thanks to this issue! In the next version the feature will be available. You can check this PR to know when it will be merged [https://github.com/rsksmart/rsk-cli/pull/19](https://github.com/rsksmart/rsk-cli/pull/19)
