### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by SwapMarket** [rsksmart/rsk-cli#18]
Hello. How can I debug this? Debian 12 in UTM on Intel Macbook:

```
user@mac:~$ rsk-cli --version
Segmentation fault
user@mac:~$ node -v
v20.18.0
```

**Comment by chrisarevalodev** [comment]
Hey! Thanks for the observation. The `--version` command was indeed missing. It was already added and will be available on the next version of the CLI. Thanks again!
